refresh_rate: 5 seconds

appenders:
  console:
    kind: console
    encoder:
      pattern: "{d(%+)(local)} [{t}] {h({l})} {M}:{m}{n}"
    filters:
      - kind: threshold
        level: info
  file:
    kind: file
    path: info.log
    encoder:
      pattern: "{d} [{t}] {l} {M}:{m}{n}"

root:
  appenders:
    - console
    - file

loggers:
  multi_logger_config::a:
    level: info
    appenders:
      - file
    additive: true